# Continuous integration tasks running on Cirrus CI.
#
# This is currently used for testing under FreeBSD, which is not available at
# the other CI providers already used by SOCI.
env:
  SOCI_CI: true
  SOCI_CI_BACKEND: empty
  SOCI_CI_BRANCH: ${CIRRUS_BRANCH}
  SOCI_SOURCE_DIR: /tmp/cirrus-ci-build
  # Using Boost results in tons of warnings under FreeBSD.
  WITH_BOOST: OFF

task:
  name: Cirrus CI / Empty FreeBSD
  freebsd_instance:
    image_family: freebsd-13-0
  install_script: ./scripts/ci/install.sh
  before_build_script: ./scripts/ci/before_build.sh
  build_script: ./scripts/ci/build.sh
  test_script: ./scripts/ci/test.sh
