# .travis.yml - config file SOCI CI at https://travis-ci.org/

language: cpp

compiler:
  - gcc

branches:
  only:
    - master

script: mkdir -p src/build && cd src/build && cmake .. && make

notifications:
  email:
    recipients:
      - mateusz@loskot.net
    on_success: [always] # default: change
    on_failure: [always] # default: always

  irc: "irc.freenode.org#soci"
