# .travis.yml
# Configure Travis CI service to build SOCI library, http://github.com/SOCI
#
# Copyright (c) 2013 Mateusz Loskot <mateusz@loskot.net>
#
language: cpp

compiler:
  - g++
  #- clang

services:
  - mysql
  - postgresql

env:
  - SOCI_TRAVIS_BACKEND=postgression

matrix:
  fast_finish: true
  allow_failures:
    - env: SOCI_TRAVIS_BACKEND=postgression

before_install: ./bin/ci/before_install.sh
before_script: ./bin/ci/before_script.sh
script: ./bin/ci/script.sh

notifications:
  irc:
    channels:
      - "irc.freenode.org#soci"
