# .travis.yml - config file SOCI CI at https://travis-ci.org/

language: cpp

compiler:
  - g++

branches:
  only:
    - master

services:
  - mysql
  - postgresql

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-dev libboost-date-time-dev libmyodbc unixodbc-dev odbc-postgresql firebird2.5-super firebird2.5-dev

before_script:
  - mysql --version
  - mysql -e 'create database soci_test;'
  - psql --version  
  - psql -c 'create database soci_test;' -U postgres

script:
  - mkdir -p src/_build
  - cd src/_build
  - cmake -DSOCI_TESTS=ON -DSOCI_EMPTY_TEST_CONNSTR:STRING="dummy connection" -DSOCI_MYSQL_TEST_CONNSTR:STRING="db=soci_test" -DSOCI_POSTGRESQL_TEST_CONNSTR:STRING="dbname=soci_test user=postgres" -DSOCI_SQLITE3_TEST_CONNSTR:STRING="soci_test.db" -DSOCI_ODBC_TEST_POSTGRESQL_CONNSTR="FILEDSN=${PWD}/../backends/odbc/test/test-postgresql.dsn;" -DSOCI_ODBC_TEST_MYSQL_CONNSTR="FILEDSN=${PWD}/../backends/odbc/test/test-mysql.dsn;" ..
  - cmake --build .
  - ctest -V --output-on-failure .

notifications:
  email:
    recipients:
      - mateusz@loskot.net
  on_success: always # [always|never|change] # default: change
  on_failure: always # [always|never|change] # default: always

  irc:
    channels:
      - "irc.freenode.org#soci"
