# .travis.yml - config file SOCI CI at https://travis-ci.org/

language: cpp

compiler:
  - gcc

branches:
  only:
    - master

script: mkdir -p src/build && cd src/build && cmake .. && make

notifications:
  email:
    recipients:
      - mloskot@gmail.com
      - mateusz@loskot.net
  on_success: always # [always|never|change] # default: change
  on_failure: always # [always|never|change] # default: always
