# Continuous integration workflow for SOCI.
name: GitHub CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - appveyor.yml
      - .travis.yml
  pull_request:
    branches:
      - master
    paths-ignore:
      - appveyor.yml
      - .travis.yml

jobs:
  build:
    runs-on: ${{ matrix.runner || 'ubuntu-16.04' }}
    name: ${{ matrix.backend }} ${{ matrix.cxx_std }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Unsupported: db2exc package is only available in Ubuntu 14.04 not
          # supported by GitHub Actions any longer.
          # backend: db2
          - backend: empty
            cxx_std: 98
            test_release_package: true
          - backend: empty
            cxx_std: 11
          - backend: firebird
          - backend: mysql
          - backend: odbc
          - backend: postgresql
          - backend: sqlite3
          - backend: valgrind
          - backend: oracle
            no_boost: true

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 5432:5432

    env:
      SOCI_CI: true
      SOCI_CI_BACKEND: ${{ matrix.backend }}
      PGHOST: localhost
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          set_env_var() {
            echo "Setting environment variable $1=$2"
            echo $1=$2 >> $GITHUB_ENV
          }

          set_env_var SOCI_CI_BRANCH $GITHUB_REF
          set_env_var SOCI_SOURCE_DIR $GITHUB_WORKSPACE
          set_env_var SOCI_SOURCE_DIR `pwd`
          if [ "${{matrix.no_boost}}" = true ]; then
            set_env_var WITH_BOOST OFF
          fi
          if [ "${{matrix.cxx_std}}" != '' ]; then
            set_env_var CMAKE_CXX_STANDARD ${{matrix.cxx_std}}
          fi
          if [ "${{matrix.test_release_package}}" = true ]; then
            set_env_var TEST_RELEASE_PACKAGE YES
          fi

      - name: Before install
        env:
          SOCI_CI_PACKAGES: cmake
        run: ./scripts/ci/before_install.sh

      - name: Before build
        run: ./scripts/ci/before_build.sh

      - name: Build
        run: ./scripts/ci/build.sh

      - name: Test
        run: ./scripts/ci/test.sh
